Add: User앱 생성, 회원가입/로그인 엔드포인트 구현, 유저 데코레이터 구현
wecode-bootcamp-korea/15-2nd-myDongMyoTrip-backend pull request #2
Opened 2020-12-30 13:07 UTC by jacobjuhyunglee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- User앱 생성, 회원가입/로그인 엔드포인트 구현, 유저 데코레이터 구현하였습니다.
		 
## 수정 사항들 자세한 내용
- User 앱 생성해주었습니다.
- 정규표현식 이용해 마이리얼트립과 같은 방식의 회원가입을
  구현하였습니다 (이메일, 패스워드 모든 조건 확인).
- 로그인 엔드포인트 구현했습니다(access_token 리턴 확인).
- 유저 데코레이터 구현했습니다 (데코레이터 테스트 완료했습니다).

## 기타 질문 및 특이 사항
- 처음으로 데코레이터, 정규표현식을 작성하였는데(참고를 많이 했지만) 이상한 부분 있으시면 리뷰 부탁드립니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-04 02:30 UTC, lordmyshepherd requested changes

2021-01-04 02:30 UTC, lordmyshepherd commented on user/tests.py
> +        )
모든 테스트케이스 마다 Client 객체를 새로 생성하는 것 보다는 처음에 만들어놓은 client 객체를 참조해서 사용하는게 메모리 효율적입니다.

```
def setUp(self):
        self.client = Client()
```

2021-01-04 02:30 UTC, lordmyshepherd commented on user/tests.py
> +        )
이에 맞게 아래 테스트케이스의 Client 부분을 수정해주세요.

2021-01-04 02:30 UTC, lordmyshepherd commented on user/views.py
> +            or re.match(REGEX_PASSWORD_3, password) or re.match(REGEX_PASSWORD_4, password)
해당 View에서는 API 역할을 수행할 수 있는 handler method(get, post, patch 등..)만 구현하는 것이 좋습니다.
validate 함수는 utils.py나 외부 모듈로 이동해주세요.

2021-01-04 02:30 UTC, lordmyshepherd commented on user/views.py
> +                user = User.objects.get(social_id = social_id)
`get_or_create()`를 제대로 사용하는 방법을 찾아보시면 좋을 것 같아요~

2021-01-04 02:30 UTC, lordmyshepherd commented on user/views.py
> +                    social_platform = SocialPlatform.objects.get(platform='kakao'),
platform table을 만들어서 여러 플렛폼에 대해서 소셜로그인을 구현한다면, User와 SocialPlatform과 social_id의 관계를 다시한번 생각해보고 social_id가 어느 테이블에 있어야되는지 고민해보면 좋을 것 같습니다!

2021-01-04 02:30 UTC, lordmyshepherd commented on user/tests.py
> +    def test_kakao_sign_in_success(self, mocked_request):
faile 케이스 추가해주세요~

2021-01-04 02:30 UTC, lordmyshepherd commented on user/tests.py
> +    def test_signupview_post_success(self):
email 인증에 대한 unittest가 빠진 것 같습니다!

2021-01-04 03:43 UTC, jacobjuhyunglee commented on user/views.py
> +                    social_platform = SocialPlatform.objects.get(platform='kakao'),
네 사실 저도 생각했던 부분입니다! 
아마 제가 병민님 말씀을 이해한게 맞다면, 한 유저가 네이버, 카카오등 여러 소셜 플랫폼 아이디를 가질 수 있기 때문에 소셜 플랫폼 테이블을 빼서 platform name, social_id, user(foreignkey)로 만들어줘야 한다는 말씀이신 것 같은데 맞나요? 

이 부분을 처음에 고민했었는데, 카카오 외에 구현을 안할 것 같아 우선 저렇게 만들어준 것 같습니다.
하지만 또 모델링은 구현하는걸 넘어서 전체적인 시야를 가지고 모델링해야하니.. 위 해결책이 맞다면 그렇게 해줘야될 것 같기두 하구요.

models.py를 수정하는게 좋을까요?

2021-01-04 04:23 UTC, jacobjuhyunglee commented on user/tests.py
> +        )
오오..!!! 감사합니다 :) 수정했습니다.

2021-01-04 05:16 UTC, jacobjuhyunglee commented on user/tests.py
> +    def test_kakao_sign_in_success(self, mocked_request):
invalid_token / KeyError 추가했습니다!

2021-01-04 07:22 UTC, jacobjuhyunglee commented on user/tests.py
> +    def test_signupview_post_success(self):
병민님! 이부분 어렵다고 하셨는데, 항공권 필수 구현 기능들 먼저 마무리하고 이 부분 작성해보아도 될까요?
절대 이번에는 다시 안넘어가겠습니다...😊

2021-01-04 12:18 UTC, jacobjuhyunglee commented on user/views.py
> +            or re.match(REGEX_PASSWORD_3, password) or re.match(REGEX_PASSWORD_4, password)
수정하였습니다!

2021-01-04 16:23 UTC, jacobjuhyunglee commented on user/views.py
> +                user = User.objects.get(social_id = social_id)
병민님 질문한대로 obj, created 사용법 찾아봐서 `user, _` 라고 작성했는데 구글링 해보니 `user = User~`, 마지막에 [0] (created가 boolean flag라 0, 1 반환)같은 방법도 사용가능한 것 같은데, 답볍 중에는 [0]을 붙혀주는게 좀 형식적인 방법이라 처음처럼 underscore을 써주는 게 더 좋은 방법이란 결과들을 얻었는데 어떤가요?? 

그리고 제가 사용한 방법이 맞을까요 ^..^?

2021-01-05 02:28 UTC, lordmyshepherd commented on user/views.py
> +                    social_platform = SocialPlatform.objects.get(platform='kakao'),
SocialPlatform으로 테이블을 분리해주셨으면, 수정해주시는게 맞을 것 같습니다~

2021-01-05 02:28 UTC, lordmyshepherd approved these changes

2021-01-05 04:37 UTC, jacobjuhyunglee commented on user/views.py
> +                    social_platform = SocialPlatform.objects.get(platform='kakao'),
SocialPlatform 테이블에서 플랫폼, 소셜아이디, 유저테이블 담고있도록 수정해주었습니다!

2021-01-05 06:11 UTC, lordmyshepherd requested changes

2021-01-05 06:11 UTC, lordmyshepherd commented on user/views.py
> +                )
`get_or_create()`를 사용할 때, 인수로 `email`, `name`, `is_location_agreed`, `is_promotion_agreed` ..와 같은 값들도 함께 전달할 경우, 만약에 카카오에서 name을 수정해서 "A" -> "B"로 변경되었다면, 해당 유저가 다음에 로그인할 때 어떻게 될까요?

[hint]
```suggestion
                user, created = User.objects.get_or_create(
                    social_id = social_id
                )
                if created:
                    user.email = email,
                    user.name = name,
                    is_loca ..
                
                access_token
```

2021-01-06 07:50 UTC, jacobjuhyunglee commented on user/views.py
> +                )
병민님 저번에 이해시켜주셔서 감사합니다! 
이메일 인증 유닛테스트 완료 후 푸시하겠습니당~

2021-01-08 03:07 UTC, merged