Add: Flight 앱 생성, 카테고리 API 구현, 유닛 테스트 완료
wecode-bootcamp-korea/15-2nd-myDongMyoTrip-backend pull request #5
Opened 2021-01-02 06:16 UTC by jacobjuhyunglee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- Flight 앱 생성, 카테고리 API 구현, 유닛 테스트 완료 하였습니다.
- 	 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 마이리얼트립 항공권 검색에 필요한 카테고리(Region-Airport) API 구현했습니다.
- API 유닛 테스트 완료했습니다.

## 기타 질문 및 특이 사항
- 유닛 테스트를 습관화 하기 위해 간단한 API지만 유닛테스트 완료 후 PR 작성했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-04 08:04 UTC, lordmyshepherd requested changes

2021-01-04 08:04 UTC, lordmyshepherd commented on flight/views.py
> +                q &= q(seat_class_id=seat_class_id)
```suggestion
            if seat_class_id:
                q &= Q(seat_class_id=seat_class_id)
```

2021-01-04 08:04 UTC, lordmyshepherd commented on flight/views.py
> +            flights = Flight.objects.select_related('airline', 'departure_airport', 'arrival_airport', 'detailed_price', 'seat_class').filter(q).order_by(sorting_type_set[order])
코드가 많이 깔끔해지셨네요~👍

2021-01-04 08:04 UTC, lordmyshepherd commented on flight/tests.py
> +        flights = Flight.objects.select_related('airline', 'departure_airport', 'arrival_airport', 'detailed_price', 'seat_class')
이 코드는 왜 필요한가요?
```suggestion
        flights = Flight.objects.select_related('airline', 'departure_airport', 'arrival_airport', 'detailed_price', 'seat_class')
```

2021-01-04 08:05 UTC, lordmyshepherd commented
filter, ordering 테스트 케이스도 추가해주세요~

2021-01-04 10:10 UTC, jacobjuhyunglee commented on flight/views.py
> +                q &= q(seat_class_id=seat_class_id)
수정하였습니다!

2021-01-04 10:10 UTC, jacobjuhyunglee commented on flight/views.py
> +            flights = Flight.objects.select_related('airline', 'departure_airport', 'arrival_airport', 'detailed_price', 'seat_class').filter(q).order_by(sorting_type_set[order])
감사합니다!!

2021-01-04 10:16 UTC, jacobjuhyunglee commented
> filter, ordering 테스트 케이스도 추가해주세요~

2021-01-04 10:18 UTC, jacobjuhyunglee commented on flight/tests.py
> +        flights = Flight.objects.select_related('airline', 'departure_airport', 'arrival_airport', 'detailed_price', 'seat_class')
원래 region-airport처럼 테스트 할려고 해서 원래 코드에 있는 코드들을 옮겨 적었다가 방식을 바꾸고 안 지웠었네요..! 삭제 완료했습니다

2021-01-05 05:38 UTC, lordmyshepherd requested changes

2021-01-05 05:38 UTC, lordmyshepherd commented on flight/tests.py
> +    def test_flightlistview_get_success(self):
flight view에서 filter 기능도 테스트케이스에 추가해주시면 좋을 것 같습니다!
전부 추가하실 필요는 없고 한가지 정도만 추가해주세요~

2021-01-06 07:51 UTC, jacobjuhyunglee commented on flight/tests.py
> +    def test_flightlistview_get_success(self):
추가했습니다!

2021-01-08 03:08 UTC, jamessoun93 commented
conflict 해결해주세요!

2021-01-08 03:19 UTC, merged