Add: Accommodation 숙소디테일 API 구현, 유닛테스트 완료
wecode-bootcamp-korea/15-2nd-myDongMyoTrip-backend pull request #8
Opened 2021-01-04 01:42 UTC by hwukjunwoo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-04 07:53 UTC, lordmyshepherd requested changes

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/migrations/0001_initial.py
> +<<<<<<< HEAD
conflict가 해결하시다가 넘어간 부분이 있네요.
다시 수정해서 올려주세요~

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/tests.py
> +=======
여기도 conflict가 있네요. 수정해주세요~

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/views.py
> +from .models          import  (
👍

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/views.py
> +=======
여기도 conflict가 있습니다.

2021-01-04 07:53 UTC, lordmyshepherd commented on csv_file/accommodation.csv
> +id,name,price,description,number_of_guest,star_rating,check_in,check_out,address,host_id
csv 파일은 git에 추가되지 않도록 수정해주세요~

2021-01-04 07:53 UTC, lordmyshepherd commented on csv_file/accommodation_themes.csv
> +Id,accommodation_id,theme_id,,,
마찬가지 입니다.

2021-01-04 07:53 UTC, lordmyshepherd commented on csv_file/accommodationdormitory.csv
> +id,accommodation_id,dormitory_id
마찬가지 입니다.

2021-01-04 07:53 UTC, lordmyshepherd commented on csv_file/accommodationfacility.csv
> +id,accommodation_id,shared_facility_id
마찬가지 입니다.

2021-01-04 07:53 UTC, lordmyshepherd commented on csv_file/accommodationimage.csv
> +1,https://www.lorempixel.com/45/93,3
마찬가지 입니다.

2021-01-04 07:53 UTC, lordmyshepherd commented on flight/migrations/0001_initial.py
> +<<<<<<< HEAD
conflict 해결해주세요~

2021-01-04 07:53 UTC, lordmyshepherd commented on user/migrations/0001_initial.py
> +<<<<<<< HEAD
마찬가지로 conflict 해결해주세요~

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/tests.py
> +class AccommodationDetail(TestCase):
데이터를 생성했다가 지우기만 하는건가요??
`AccommodationDetailView`에 대한 테스트코드를 작성해주세요~

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/views.py
> +    def get(self, request, accommodation_id):
restful하게 잘 구현해 주셨습니다~ 👍

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/views.py
> +            accommodation_detail = [
전체를 리스트로 반환하는 이유가 무엇인가요?

2021-01-04 07:53 UTC, lordmyshepherd commented on accommodation/views.py
> +                ],
여기서도 host 정보를 list로 만드는 이유가 있나요? 
```suggestion
                'host'                      : [
                    {
                        'name'      : accommodation.host.name,
                        'image_url' : accommodation.host.image_url
                    }
                ],
```

2021-01-05 05:43 UTC, lordmyshepherd requested changes

2021-01-05 05:43 UTC, lordmyshepherd commented on accommodation/tests.py
> +    def test_accommodationdetailview_get_fail(self):
👍

2021-01-05 05:43 UTC, lordmyshepherd commented on accommodation/tests.py
> +    def test_accommodationdetailview_get_not_found(self):
`def test_accommodationdetailview_get_fail` 테스트케이스와 어떤 점이 다른건가요?

2021-01-05 05:43 UTC, lordmyshepherd commented on accommodation/views.py
> +                                'user_id'     : User.objects.get(id=review.user_id).name,
review객체에서 접근해서 user name을 가져올 수 있는 방법은 없나요?

2021-01-05 07:20 UTC, hwukjunwoo commented on accommodation/tests.py
> +    def test_accommodationdetailview_get_not_found(self):
@lordmyshepherd 큰 차이점은 없지만  fail일때는 정보에 require정보가 안들어왔을때  fail이 뜨고  not_found일때는 정보가 없을때나 돌발상황이 생기면 not_found가 생긴다 생각을했는데 그렇게 접근하면 안되나요? .

2021-01-08 03:39 UTC, lordmyshepherd requested changes

2021-01-08 03:39 UTC, lordmyshepherd commented on accommodation/migrations/0002_auto_20210102_0210.py
> +=======
여전히 컨플릭트 해결 안된 부분이 남아있는 것 같아요!

2021-01-08 04:22 UTC, lordmyshepherd requested changes

2021-01-08 04:22 UTC, lordmyshepherd commented on myDongMyoTrip/urls.py
> +    path('accommodation', include('accommodation.urls')),
여기도 해결해주세요~

2021-01-08 04:22 UTC, lordmyshepherd commented on flight/migrations/0002_auto_20210104_2027.py
> +>>>>>>> 3c8729f... Add: Accommodation 숙소디테일 API 구현, 유닛테스트 완료:flight/migrations/0002_auto_20210104_2027.py
여기도 해결해주세요~

2021-01-08 04:44 UTC, lordmyshepherd approved these changes

2021-01-08 04:47 UTC, lordmyshepherd approved these changes

2021-01-08 04:48 UTC, lordmyshepherd commented
LGTM 👍

2021-01-08 04:48 UTC, merged